=== willfarrell/aws-events/events/apig/http/schema.event.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "https://schema.aws/apig/http/event",
	"title": "API Gateway HTTP Event",
	"description": "",
	"$defs": {
		"method": {
			"$ref": "https://schema.aws/defs#/$defs/httpMethod",
			"$comment": "GET"
		},
		"path": {
			"$ref": "https://schema.aws/defs#/$defs/httpPath",
			"$comment": "/path/to/endpoint"
		},
		"routeKey": {
			"$comment": "GET /path/to/endpoint or $default"
		},
		"pathParameters": {
			"type": "object",
			"unevaluatedProperties": false,
			"properties": {},
			"required": []
		},
		"headers": {
			"allOf": [
				{
					"$ref": "https://schema.aws/defs#/$defs/httpHeaders"
				},
				{
					"description": "Add in overrides below",
					"type": "object",
					"unevaluatedProperties": false,
					"properties": {
						"accept": true,
						"accept-encoding": true,
						"accept-language": true,
						"authorization": true,
						"cache-control": true,
						"cloudfront-is-mobile-viewer": true,
						"cloudfront-is-smarttv-viewer": true,
						"cloudfront-is-tablet-viewer": true,
						"cloudfront-viewer-city": true,
						"cloudfront-viewer-country-name": true,
						"cloudfront-viewer-country-region-name": true,
						"cookie": true,
						"content-length": true,
						"host": true,
						"if-none-match": true,
						"origin": true,
						"pragma": true,
						"sec-ch-ua": true,
						"sec-ch-ua-platform": true,
						"user-agent": true,
						"via": true,
						"x-amz-cf-id": true,
						"x-amz-content-sha256": true,
						"x-amz-date": true,
						"x-amz-security-token": true,
						"x-amz-source-account": true,
						"x-amz-source-arn": true,
						"x-amzn-tls-cipher-suite": true,
						"x-amzn-tls-version": true,
						"x-amzn-trace-id": true,
						"x-forwarded-for": true,
						"x-forwarded-port": true,
						"x-forwarded-proto": true
					},
					"required": [
						"accept",
						"user-agent"
					]
				}
			]
		},
		"cookies": {
			"type": "array",
			"unevaluatedItems": false,
			"items": {
				"$ref": "https://schema.aws/defs#/$defs/httpCookie"
			},
			"uniqueItems": true,
			"minItems": 0,
			"maxItems": 5
		},
		"queryStringParameters": {
			"type": "object",
			"unevaluatedProperties": true,
			"patternProperties": {
				"^[a-z]+$": {
					"$ref": "https://schema.aws/defs#/$defs/httpQueryStringValue"
				}
			},
			"maxProperties": 32,
			"required": []
		},
		"isBase64Encoded": {
			"const": false
		},
		"body": {
			"$ref": "https://schema.aws/defs#/$defs/string",
			"type": "string",
			"pattern": "^[\\p{L}\\p{N}\\p{P}\\p{M}\\p{S} \\r\\n]+$",
			"maxLength": 8096
		},
		"stage": {
			"const": "$default"
		}
	},
	"type": "object",
	"unevaluatedProperties": false,
	"properties": {
		"version": {
			"const": "2.0"
		},
		"routeKey": {
			"$ref": "#/$defs/routeKey"
		},
		"rawPath": {
			"$ref": "#/$defs/path"
		},
		"rawQueryString": {
			"$ref": "https://schema.aws/defs#/$defs/httpQueryString"
		},
		"cookies": {
			"$ref": "#/$defs/cookies"
		},
		"headers": {
			"$ref": "#/$defs/headers"
		},
		"requestContext": {
			"type": "object",
			"unevaluatedProperties": false,
			"properties": {
				"accountId": {
					"$ref": "https://schema.aws/defs#/$defs/accountId"
				},
				"apiId": {
					"type": "string",
					"pattern": "^[a-z0-9]+$",
					"minLength": 2,
					"maxLength": 32
				},
				"authorizer": {
					"type": "object",
					"unevaluatedProperties": false,
					"properties": {
						"jwt": {
							"type": "object",
							"unevaluatedProperties": false,
							"properties": {
								"claims": {
									"$ref": "https://schema.aws/defs#/$defs/objectOfStrings"
								},
								"scopes": {
									"$ref": "https://schema.aws/defs#/$defs/arrayOfString"
								}
							},
							"required": [
								"claims"
							]
						},
						"iam": {
							"type": "object",
							"unevaluatedProperties": false,
							"properties": {
								"accessKey": {
									"$ref": "https://schema.aws/defs#/$defs/authorizerIamAccessKey"
								},
								"accountId": {
									"$ref": "https://schema.aws/defs#/$defs/accountId"
								},
								"callerId": {
									"$ref": "https://schema.aws/defs#/$defs/authorizerIamUserId"
								},
								"cognitoIdentity": {
									"type": [
										"object",
										"null"
									],
									"unevaluatedProperties": false,
									"properties": {
										"amr": {
											"$ref": "https://schema.aws/defs#/$defs/arrayOfString"
										},
										"identityId": {
											"$ref": "https://schema.aws/defs#/$defs/string"
										},
										"identityPoolId": {
											"$ref": "https://schema.aws/defs#/$defs/string"
										}
									},
									"required": [
										"amr",
										"identityId",
										"identityPoolId"
									]
								},
								"principalOrgId": {
									"oneOf": [
										{
											"$ref": "https://schema.aws/defs#/$defs/accountId"
										},
										{
											"const": ""
										}
									]
								},
								"userArn": {
									"$ref": "https://schema.aws/defs#/$defs/arn"
								},
								"userId": {
									"$ref": "https://schema.aws/defs#/$defs/authorizerIamUserId"
								}
							},
							"required": []
						},
						"lambda": {
							"$ref": "https://schema.aws/defs#/$defs/objectOfStrings"
						}
					},
					"required": []
				},
				"domainName": {
					"$ref": "https://schema.aws/defs#/$defs/httpHostname"
				},
				"domainPrefix": {
					"type": "string",
					"pattern": "^[a-z0-9]+$",
					"minLength": 2,
					"maxLength": 32
				},
				"http": {
					"type": "object",
					"unevaluatedProperties": false,
					"properties": {
						"method": {
							"$ref": "#/$defs/method"
						},
						"path": {
							"$ref": "#/$defs/path"
						},
						"protocol": {
							"$ref": "https://schema.aws/defs#/$defs/httpProtocol"
						},
						"sourceIp": {
							"$ref": "https://schema.aws/defs#/$defs/httpIP"
						},
						"userAgent": {
							"$ref": "https://schema.aws/defs#/$defs/httpHeaders/properties/user-agent"
						}
					},
					"required": [
						"method",
						"path",
						"protocol",
						"sourceIp",
						"userAgent"
					]
				},
				"requestId": {
					"$ref": "https://schema.aws/defs#/$defs/requestId"
				},
				"routeKey": {
					"$ref": "#/$defs/routeKey"
				},
				"stage": {
					"$ref": "#/$defs/stage"
				},
				"time": {
					"$ref": "https://schema.aws/defs#/$defs/stringAWSTimestamp"
				},
				"timeEpoch": {
					"$ref": "https://schema.aws/defs#/$defs/timeEpochInMilliseconds"
				}
			},
			"required": [
				"accountId",
				"apiId",
				"domainName",
				"domainPrefix",
				"http",
				"requestId",
				"routeKey",
				"stage",
				"time",
				"timeEpoch"
			]
		},
		"isBase64Encoded": {
			"$ref": "#/$defs/isBase64Encoded"
		},
		"body": {
			"$ref": "#/$defs/body"
		},
		"pathParameters": {
			"$ref": "#/$defs/pathParameters"
		},
		"queryStringParameters": {
			"$ref": "#/$defs/queryStringParameters"
		},
		"stageVariables": {
			"$ref": "#/$defs/stage"
		}
	},
	"required": [
		"version",
		"routeKey",
		"rawPath",
		"rawQueryString",
		"headers",
		"requestContext",
		"isBase64Encoded"
	]
}

=== willfarrell/aws-events/events/apig/http/tests/data.event.fcturl-2.json
{
	"version": "2.0",
	"routeKey": "$default",
	"rawPath": "/api/v3/series/yp",
	"rawQueryString": "p=f420ad03-11fe-5519-af99-213b6ce4c8b5&l=fd3df166-361c-51c7-b9bd-676d4cdd8d2d&z=0&draft=true",
	"cookies": [
		"__Host-sid=G8MHgZDgJXNKpL6Gc0l3NW.QGydOtBYbPw19Q2LWBx%2FdanseYEVvO%2BMOcCP3cx6E8nCoLTvBuJQQ5FVDIo5K7a9"
	],
	"headers": {
		"x-amz-content-sha256": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
		"x-amzn-tls-version": "TLSv1.2",
		"x-amz-source-account": "070822334555",
		"x-forwarded-port": "443",
		"x-amz-security-token": "IQoJb3JpZ2luX2VjEBYaDGNhLWNlbnRyYWwtMSJHMEUCIF4oM3OYlsC1loGWlTTpJV8pTzECeqSK9ExPX9/6mx6NAiEA+JNLBS1dUpE5tXXnDahnn9k1ZWRQEtQyOEWICtQRFgIqvgIIr///////////ARAAGgw4NTYzNjkwNTMxODEiDFz/S3PPacwOM8e84yqSAg3HQYk4JphqDTn0ZB6TjRKxf1zRriGPp/QWB17SY6q1eShdqDDzjw6txn0fMh4ClZBEedhTKw27rFUrZzokLaxiij+WvnVNi9jJufEHL+uxUKyGhnalqJenZ3nVCMipyvBkr5WT3vQli645VPAdevga3ZoZvm9akFk8BB/90FYnfRDywShPGrv1RutJpYqIof647MLGjH79TNIkGC+929vfbB6pdvNodBJW0oim3I17cTHwIRdafwwqrMUpGp5BzEZ13eaOncdFFWb38PiC70lFwJ69FPXNjgB9OyP6ydLNVmK+8Ojj3gR74Dhd9NjfYLhpujjjGhuwkVUeilFu5vvzcRNeG3jA8WFSNNgCVcaUxikwpd3+uQY6jwHJwzLntr8PHaqfxFGD0SdYDBrelTgN2qyzdN2nbLRWjHKxZfzFX0oTJ8u6w6sppij+CCW+M01ycuRmLXUpnxYYBJdQDlPVn7p3f2nRfOeB75dLcHOdOM6iYEic6ddrE4kTLhGR/HA5vpQFjw+D0h8Xu2bqqEL0QaeuSTuU1eAstpsMkoZSBmfejj1OIRQ2Zg==",
		"via": "1.1 3e2f24f1d3a153797ece2b5ee8de204a.cloudfront.net (CloudFront)",
		"x-amzn-tls-cipher-suite": "ECDHE-RSA-AES128-GCM-SHA256",
		"cloudfront-viewer-country-name": "Canada",
		"host": "cvgn7vcjityqwtalgylnra4tte0kgntv.lambda-url.ca-central-1.on.aws",
		"cache-control": "no-cache",
		"cloudfront-viewer-city": "Calgary",
		"cookie": "__Host-sid=G8MHgZDgJXNKpL6Gc0l3NW.QGydOtBYbPw19Q2LWBx%2FdanseYEVvO%2BMOcCP3cx6E8nCoLTvBuJQQ5FVDIo5K7a9",
		"x-amz-date": "20241121T233950Z",
		"x-forwarded-proto": "https",
		"accept-language": "en-CA",
		"x-forwarded-for": "198.48.146.202",
		"pragma": "no-cache",
		"accept": "application/json",
		"x-amz-source-arn": "arn:aws:cloudfront::070822334555:distribution/E2M0F77L5HS7MV",
		"cloudfront-is-smarttv-viewer": "false",
		"sec-ch-ua": "\"Chromium\";v=\"130\", \"Google Chrome\";v=\"130\", \"Not?A_Brand\";v=\"99\"",
		"x-amzn-trace-id": "Root=1-673fc4c6-433d55075145b23968c4a698",
		"cloudfront-is-tablet-viewer": "false",
		"sec-ch-ua-platform": "\"macOS\"",
		"cloudfront-viewer-country-region-name": "Alberta",
		"accept-encoding": "gzip, deflate, br, zstd",
		"x-amz-cf-id": "QNM5Ujhq6FN4Vv_bqSAXL7a8bcMsNLeNfg3XDB3mVQ220twmEzA4gg==",
		"user-agent": "Amazon CloudFront",
		"cloudfront-is-mobile-viewer": "false"
	},
	"queryStringParameters": {
		"p": "f420ad03-11fe-5519-af99-213b6ce4c8b5",
		"draft": true,
		"z": 0,
		"l": "fd3df166-361c-51c7-b9bd-676d4cdd8d2d"
	},
	"requestContext": {
		"accountId": "856369053181",
		"apiId": "cvgn7vcjityqwtalgylnra4tte0kgntv",
		"authorizer": {
			"iam": {
				"accessKey": "ASIA4OY4SXX6S4RFSHWL",
				"accountId": "856369053181",
				"callerId": "AROA4OY4SXX6VEIZRJRCJ:EdgeCredentialsProxy+EdgeHostAuthenticationClient-YVR52-P2",
				"cognitoIdentity": null,
				"principalOrgId": "",
				"userArn": "arn:aws:sts::856369053181:assumed-role/OriginAccessControlRole/EdgeCredentialsProxy+EdgeHostAuthenticationClient-YVR52-P2",
				"userId": "AROA4OY4SXX6VEIZRJRCJ:EdgeCredentialsProxy+EdgeHostAuthenticationClient-YVR52-P2"
			}
		},
		"domainName": "cvgn7vcjityqwtalgylnra4tte0kgntv.lambda-url.ca-central-1.on.aws",
		"domainPrefix": "cvgn7vcjityqwtalgylnra4tte0kgntv",
		"http": {
			"method": "GET",
			"path": "/api/v3/series/yp",
			"protocol": "HTTP/1.1",
			"sourceIp": "3.172.4.71",
			"userAgent": "Amazon CloudFront"
		},
		"requestId": "a80741ae-6a20-4c60-99d4-3da54ba27950",
		"routeKey": "$default",
		"stage": "$default",
		"time": "21/Nov/2024:23:39:50 +0000",
		"timeEpoch": 1732232390435
	},
	"isBase64Encoded": false,
	"pathParameters": {}
}

=== willfarrell/aws-events/events/apig/http/tests/data.event.fcturl-1.json
{
	"version": "2.0",
	"routeKey": "$default",
	"rawPath": "/img/cms/b20436093b9dfa6f52b6e6f2af77a3c2bb243d60-6688x5284.png",
	"rawQueryString": "w=1280&fm=avif",
	"headers": {
		"x-amz-content-sha256": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
		"x-amzn-tls-version": "TLSv1.2",
		"x-amz-date": "20241118T231553Z",
		"x-forwarded-proto": "https",
		"accept-language": "en-CA,en;q=0.9",
		"x-amz-source-account": "000000000000",
		"x-forwarded-port": "443",
		"x-forwarded-for": "111.44.111.222",
		"x-amz-security-token": "IQoJb3JpZ2luX2VjEMr//////////wEaCXVzLXdlc3QtMiJGMEQCIGHvAFvvFs7lhHEinDltxuT4h0aC/VxvnVC6j9MJ0YL1AiBx5rGRXqGawHuhPNwiDkcnf/e/luAaq8kONZEUkxhwGSq1AghjEAAaDDg1NjM2OTA1MzE4MSIMg8jFfd38oQnXF30iKpICYNO7o43dOG1Lq3Yu3sn5lAKv9l5s53bP0kb93XQjtuFjL4ZaD5xAR467WfwngHrrq0n2tjtBAEEsQLNR6uQKUV9QakdWPjRclg2wqjhVDObR0FGj5hM8FXUZtYLtmvBwluoIzQD3+za8b68MnpFHwznu015N+4VExHnpwKIxZll3tXsj6C6cPxiiOk5kO9YP/51ReltdFS3iw2MOVBZaq2L+0cjGV/yoEKE+vDXnruyoauu3JG59RFxOCxyIM0y0xMc1hg5kPpMJvgWkcD2lBwd7A96qXRFrOAC7XDK2IgK1gKA2BpKfMmlT1hwa3ehpNEDS8b29WlDbQpTObBqvIfQbtdp1Q6u/fIyBcJ2WoOhezjDH8u25BjqQAcl9y6rMhcCZqMIkHP2Z41eKW1H7NEVsqbhGPPRvKgmhTyuFHHiTc6YpaP7iI43ZzUrVsZr9WQ/w2VLEj7VWfVop+lWSu96n34S7pjA+9d4XDW2So2fhOXwH65eN4bITJ9nKWhGQWVWSzlNHNligb5UY3+V5Nv97OeSM34Ip+GiC9XoCaEkkhy41CJNe+duzhQ==",
		"accept": "image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8",
		"via": "2.0 11111111111111111111111111111111.cloudfront.net (CloudFront)",
		"x-amz-source-arn": "arn:aws:cloudfront::000000000000:distribution/FFFFFFFFFFFFFF",
		"x-amzn-tls-cipher-suite": "ECDHE-RSA-AES128-GCM-SHA256",
		"x-amzn-trace-id": "Root=1-673bcaa9-4159c1d5486934126dd3d1b6",
		"host": "kmb523gbzhou33663lrnzbcq2a0gijmx.lambda-url.ca-central-1.on.aws",
		"x-amz-cf-id": "cRJgZ8CaegAXGjRm5oNLa9lclfACz6a7p_U_as6efsseSd7TVSC7-g==",
		"user-agent": "Amazon CloudFront"
	},
	"queryStringParameters": {
		"fm": "avif",
		"w": 1280
	},
	"requestContext": {
		"accountId": "856369053181",
		"apiId": "kmb523gbzhou33663lrnzbcq2a0gijmx",
		"authorizer": {
			"iam": {
				"accessKey": "ASIA4OY4SXX6T7IY7C3O",
				"accountId": "856369053181",
				"callerId": "AROA4OY4SXX6VEIZRJRCJ:EdgeCredentialsProxy+EdgeHostAuthenticationClient-YYC51-P1",
				"cognitoIdentity": null,
				"principalOrgId": "",
				"userArn": "arn:aws:sts::856369053181:assumed-role/OriginAccessControlRole/EdgeCredentialsProxy+EdgeHostAuthenticationClient-YYC51-P1",
				"userId": "AROA4OY4SXX6VEIZRJRCJ:EdgeCredentialsProxy+EdgeHostAuthenticationClient-YYC51-P1"
			}
		},
		"domainName": "kmb523gbzhou33663lrnzbcq2a0gijmx.lambda-url.ca-central-1.on.aws",
		"domainPrefix": "kmb523gbzhou33663lrnzbcq2a0gijmx",
		"http": {
			"method": "GET",
			"path": "/img/cms/b20436093b9dfa6f52b6e6f2af77a3c2bb243d60-6688x5284.png",
			"protocol": "HTTP/1.1",
			"sourceIp": "9.111.55.10",
			"userAgent": "Amazon CloudFront"
		},
		"requestId": "58347d7e-59dd-41f8-b991-21cfe955967b",
		"routeKey": "$default",
		"stage": "$default",
		"time": "18/Nov/2024:23:15:53 +0000",
		"timeEpoch": 1731971753774
	},
	"isBase64Encoded": false,
	"pathParameters": {}
}

=== willfarrell/aws-events/events/apig/http/tests/data.event.get-1.json
{
	"version": "2.0",
	"routeKey": "GET /api/dataset/organization",
	"rawPath": "/api/dataset/organization",
	"rawQueryString": "draft=false&q=test",
	"headers": {
		"accept": "application/json, text/plain, */*",
		"accept-language": "en-US,en;q=0.9",
		"cache-control": "no-cache",
		"cloudfront-is-mobile-viewer": "false",
		"cloudfront-is-smarttv-viewer": "false",
		"cloudfront-is-tablet-viewer": "false",
		"cloudfront-viewer-city": "Vancouver",
		"cloudfront-viewer-country-name": "Canada",
		"cloudfront-viewer-country-region-name": "Alberta",
		"content-length": "0",
		"host": "xx0xxxxxxx.execute-api.ca-central-1.amazonaws.com",
		"origin": "https://localhost",
		"pragma": "no-cache",
		"sec-ch-ua": "\"Chromium\";v=\"128\", \"Not;A=Brand\";v=\"24\", \"Google Chrome\";v=\"128\"",
		"sec-ch-ua-platform": "\"macOS\"",
		"user-agent": "Amazon CloudFront",
		"via": "3.0 ffffffffffffffffffffffffffffffff.cloudfront.net (CloudFront)",
		"x-amz-cf-id": "0j476N-JDtQabF97n1FPbM1osrDHCYbT3v_pkBvyQUiYh1dMu1pGoQ==",
		"x-amzn-trace-id": "Root=1-63969999-5a7b8b310c651aef57f5cba3",
		"x-forwarded-for": "104.205.238.229, 64.252.70.39",
		"x-forwarded-port": "443",
		"x-forwarded-proto": "https"
	},
	"queryStringParameters": {
		"draft": "false",
		"q": "test"
	},
	"requestContext": {
		"accountId": "000000000000",
		"apiId": "xx0xxxxxxx",
		"authorizer": {
			"lambda": {}
		},
		"domainName": "xx0xxxxxxx.execute-api.ca-central-1.amazonaws.com",
		"domainPrefix": "xx0xxxxxxx",
		"http": {
			"method": "GET",
			"path": "/api/dataset/organization",
			"protocol": "HTTP/1.1",
			"sourceIp": "199.0.0.202",
			"userAgent": "Amazon CloudFront"
		},
		"requestId": "fYn7Zh_-YosEMkg=",
		"routeKey": "GET /api/dataset/organization",
		"stage": "$default",
		"time": "09/Oct/2024:13:35:43 +0000",
		"timeEpoch": 1728480943026
	},
	"isBase64Encoded": false,
	"pathParameters": {}
}

=== willfarrell/aws-events/events/apig/http/tests/data.event.health.json
{
	"version": "2.0",
	"routeKey": "GET /api/health",
	"rawPath": "/api/health",
	"rawQueryString": "",
	"headers": {
		"accept": "application/vnd.api+json",
		"accept-language": "fr-FR,fr",
		"cloudfront-is-mobile-viewer": "false",
		"cloudfront-is-smarttv-viewer": "false",
		"cloudfront-is-tablet-viewer": "false",
		"cloudfront-viewer-city": "Toronto",
		"cloudfront-viewer-country-name": "Canada",
		"cloudfront-viewer-country-region-name": "Alberta",
		"content-length": "0",
		"host": "xxxxxxxxxx.execute-api.ca-central-1.amazonaws.com",
		"user-agent": "Amazon CloudFront",
		"via": "1.1 ffffffffffffffffffffffffffffffff.cloudfront.net (CloudFront)",
		"x-amz-cf-id": "AAAAAAAAAAAAAAAAAAAAAAFS232MOwxNU0MdzJIo8TTnJ9mGtGVwew==",
		"x-amzn-trace-id": "Root=1-666c5004-3715ba145d51bc6b6ac87e58",
		"x-forwarded-for": "198.0.0.202, 3.0.0.10",
		"x-forwarded-port": "443",
		"x-forwarded-proto": "https"
	},
	"requestContext": {
		"accountId": "070822334555",
		"apiId": "xs7tpmjloc",
		"domainName": "xs7tpmjloc.execute-api.ca-central-1.amazonaws.com",
		"domainPrefix": "xs7tpmjloc",
		"http": {
			"method": "GET",
			"path": "/api/health",
			"protocol": "HTTP/1.1",
			"sourceIp": "179.0.0.202",
			"userAgent": "Amazon CloudFront"
		},
		"requestId": "APFwugxw4osEJ-g=",
		"routeKey": "GET /api/health",
		"stage": "$default",
		"time": "26/Oct/2024:02:12:20 +0000",
		"timeEpoch": 1729908740226
	},
	"isBase64Encoded": false
}
